### ISSUE TITLE
FR vertical instead of horizontal

### ISSUE THREAD

**Issue by bafplus** [gerardag/person-entity-card#12]
At this point we can align the "bubles" left or centered.
Could it be possible to also align them vertical so each person's buble is below the other instead of next to each other?

**Comment by gerardag** [comment]
Hi @bafplus,

For now I haven't on mind to implement this. I would like to think how to enable this future to show chips properly, because right now, if I just add a verital align, the chips broke and not showing info as desired.

Although meanwhile you can do it using card-mod and tunning card a little bit.

I'll inform when this feature is available.

Thanks for your feedback.

**Comment by labaland** [comment]
Ad also make them bigger ?

**Comment by gerardag** [comment]
Hi,

Not for now. If you need bigger cards you can do it using card-mod plugins available from hacs.

Thanks.
